POST http://localhost:3001/users
Content-Type: application/json

{
   "name": "Alice"
}

###

GET http://localhost:3001/users
Content-Type: application/json

###

PUT http://localhost:3001/users/650087475b549bd410c68dd9
Content-Type: application/json

{
   "name": "Alice Campos"
}